% this function gets the brcs and A_eff within ddma region - 3*3 bin

function [brcs_copol_ddma,brcs_xpol_ddma,A_eff_ddma] = get_ddma_v2(brcs_copol,brcs_xpol,A_eff,sp_delay_row,sp_doppler_col)

delay_intg = floor(sp_delay_row);
delay_frac = sp_delay_row-floor(sp_delay_row);

doppler_intg = round(sp_doppler_col);
doppler_frac = sp_doppler_col-round(sp_doppler_col);

if delay_intg>=3
    delay_range = (delay_intg-2):(delay_intg+1);

elseif delay_intg<3
    delay_range = 1:4;

end

if doppler_frac>=0

    if doppler_intg<4 && doppler_intg>=2    
        doppler_range = doppler_intg-1:doppler_intg+2;

    elseif doppler_intg>=4
        doppler_range = 2:5;

    elseif doppler_intg<2
        doppler_range = 1:4;

    end

    brcs_copol_ddma  = (1-delay_frac)*(1-doppler_frac)*brcs_copol(doppler_range(1),delay_range(1)) + ...
                       (1-delay_frac)*brcs_copol(doppler_range(2),delay_range(1)) + ...
                       (1-delay_frac)*brcs_copol(doppler_range(3),delay_range(1)) + ...
                       (1-delay_frac)*doppler_frac*brcs_copol(doppler_range(4),delay_range(1)) + ...
                       (1-doppler_frac)*brcs_copol(doppler_range(1),delay_range(2)) + ...
                       brcs_copol(doppler_range(2),delay_range(2)) + ...
                       brcs_copol(doppler_range(3),delay_range(2)) + ...
                       doppler_frac*brcs_copol(doppler_range(4),delay_range(2)) + ...
                       (1-doppler_frac)*brcs_copol(doppler_range(1),delay_range(3)) + ...
                       brcs_copol(doppler_range(2),delay_range(3)) + ...
                       brcs_copol(doppler_range(3),delay_range(3)) + ...
                       doppler_frac*brcs_copol(doppler_range(4),delay_range(3)) + ...
                       (1-doppler_frac)*delay_frac*brcs_copol(doppler_range(1),delay_range(4)) + ...
                       delay_frac*brcs_copol(doppler_range(2),delay_range(4)) + ...
                       delay_frac*brcs_copol(doppler_range(3),delay_range(4)) + ...
                       delay_frac*doppler_frac*brcs_copol(doppler_range(4),delay_range(4));

    brcs_xpol_ddma   = (1-delay_frac)*(1-doppler_frac)*brcs_xpol(doppler_range(1),delay_range(1)) + ...
                       (1-delay_frac)*brcs_xpol(doppler_range(2),delay_range(1)) + ...
                       (1-delay_frac)*brcs_xpol(doppler_range(3),delay_range(1)) + ...
                       (1-delay_frac)*doppler_frac*brcs_xpol(doppler_range(4),delay_range(1)) + ...
                       (1-doppler_frac)*brcs_xpol(doppler_range(1),delay_range(2)) + ...
                       brcs_xpol(doppler_range(2),delay_range(2)) + ...
                       brcs_xpol(doppler_range(3),delay_range(2)) + ...
                       doppler_frac*brcs_xpol(doppler_range(4),delay_range(2)) + ...
                       (1-doppler_frac)*brcs_xpol(doppler_range(1),delay_range(3)) + ...
                       brcs_xpol(doppler_range(2),delay_range(3)) + ...
                       brcs_xpol(doppler_range(3),delay_range(3)) + ...
                       doppler_frac*brcs_xpol(doppler_range(4),delay_range(3)) + ...
                       (1-doppler_frac)*delay_frac*brcs_xpol(doppler_range(1),delay_range(4)) + ...
                       delay_frac*brcs_xpol(doppler_range(2),delay_range(4)) + ...
                       delay_frac*brcs_xpol(doppler_range(3),delay_range(4)) + ...
                       delay_frac*doppler_frac*brcs_xpol(doppler_range(4),delay_range(4));

    A_eff_ddma       = (1-delay_frac)*(1-doppler_frac)*A_eff(doppler_range(1),delay_range(1)) + ...
                       (1-delay_frac)*A_eff(doppler_range(2),delay_range(1)) + ...
                       (1-delay_frac)*A_eff(doppler_range(3),delay_range(1)) + ...
                       (1-delay_frac)*doppler_frac*A_eff(doppler_range(4),delay_range(1)) + ...
                       (1-doppler_frac)*A_eff(doppler_range(1),delay_range(2)) + ...
                       A_eff(doppler_range(2),delay_range(2)) + ...
                       A_eff(doppler_range(3),delay_range(2)) + ...
                       doppler_frac*A_eff(doppler_range(4),delay_range(2)) + ...
                       (1-doppler_frac)*A_eff(doppler_range(1),delay_range(3)) + ...
                       A_eff(doppler_range(2),delay_range(3)) + ...
                       A_eff(doppler_range(3),delay_range(3)) + ...
                       doppler_frac*A_eff(doppler_range(4),delay_range(3)) + ...
                       (1-doppler_frac)*delay_frac*A_eff(doppler_range(1),delay_range(4)) + ...
                       delay_frac*A_eff(doppler_range(2),delay_range(4)) + ...
                       delay_frac*A_eff(doppler_range(3),delay_range(4)) + ...
                       delay_frac*doppler_frac*A_eff(doppler_range(4),delay_range(4));            

elseif doppler_frac<0

    if doppler_intg<=4 && doppler_intg>2    
        doppler_range = doppler_intg-2:doppler_intg+1;

    elseif doppler_intg>4
        doppler_range = 2:5;

    elseif doppler_intg<=2
        doppler_range = 1:4;

    end

    brcs_copol_ddma =  (1-delay_frac)*abs(doppler_frac)*brcs_copol(doppler_range(1),delay_range(1)) + ...
                       (1-delay_frac)*brcs_copol(doppler_range(2),delay_range(1)) + ...
                       (1-delay_frac)*brcs_copol(doppler_range(3),delay_range(1)) + ...
                       (1-delay_frac)*(1-abs(doppler_frac))*brcs_copol(doppler_range(4),delay_range(1)) + ...
                       abs(doppler_frac)*brcs_copol(doppler_range(1),delay_range(2)) + ...
                       brcs_copol(doppler_range(2),delay_range(2)) + ...
                       brcs_copol(doppler_range(3),delay_range(2)) + ...
                       (1-abs(doppler_frac))*brcs_copol(doppler_range(4),delay_range(2)) + ...
                       abs(doppler_frac)*brcs_copol(doppler_range(1),delay_range(3)) + ...
                       brcs_copol(doppler_range(2),delay_range(3)) + ...
                       brcs_copol(doppler_range(3),delay_range(3)) + ...
                       (1-abs(doppler_frac))*brcs_copol(doppler_range(4),delay_range(3)) + ...
                       abs(doppler_frac)*delay_frac*brcs_copol(doppler_range(1),delay_range(4)) + ...
                       delay_frac*brcs_copol(doppler_range(2),delay_range(4)) + ...
                       delay_frac*brcs_copol(doppler_range(3),delay_range(4)) + ...
                       delay_frac*(1-abs(doppler_frac))*brcs_copol(doppler_range(4),delay_range(4));

    brcs_xpol_ddma  =  (1-delay_frac)*abs(doppler_frac)*brcs_xpol(doppler_range(1),delay_range(1)) + ...
                       (1-delay_frac)*brcs_xpol(doppler_range(2),delay_range(1)) + ...
                       (1-delay_frac)*brcs_xpol(doppler_range(3),delay_range(1)) + ...
                       (1-delay_frac)*(1-abs(doppler_frac))*brcs_xpol(doppler_range(4),delay_range(1)) + ...
                       abs(doppler_frac)*brcs_copol(doppler_range(1),delay_range(2)) + ...
                       brcs_xpol(doppler_range(2),delay_range(2)) + ...
                       brcs_xpol(doppler_range(3),delay_range(2)) + ...
                       (1-abs(doppler_frac))*brcs_xpol(doppler_range(4),delay_range(2)) + ...
                       abs(doppler_frac)*brcs_xpol(doppler_range(1),delay_range(3)) + ...
                       brcs_xpol(doppler_range(2),delay_range(3)) + ...
                       brcs_xpol(doppler_range(3),delay_range(3)) + ...
                       (1-abs(doppler_frac))*brcs_xpol(doppler_range(4),delay_range(3)) + ...
                       abs(doppler_frac)*delay_frac*brcs_xpol(doppler_range(1),delay_range(4)) + ...
                       delay_frac*brcs_xpol(doppler_range(2),delay_range(4)) + ...
                       delay_frac*brcs_xpol(doppler_range(3),delay_range(4)) + ...
                       delay_frac*(1-abs(doppler_frac))*brcs_xpol(doppler_range(4),delay_range(4));

    A_eff_ddma      =  (1-delay_frac)*abs(doppler_frac)*A_eff(doppler_range(1),delay_range(1)) + ...
                       (1-delay_frac)*A_eff(doppler_range(2),delay_range(1)) + ...
                       (1-delay_frac)*A_eff(doppler_range(3),delay_range(1)) + ...
                       (1-delay_frac)*(1-abs(doppler_frac))*A_eff(doppler_range(4),delay_range(1)) + ...
                       abs(doppler_frac)*A_eff(doppler_range(1),delay_range(2)) + ...
                       A_eff(doppler_range(2),delay_range(2)) + ...
                       A_eff(doppler_range(3),delay_range(2)) + ...
                       (1-abs(doppler_frac))*A_eff(doppler_range(4),delay_range(2)) + ...
                       abs(doppler_frac)*A_eff(doppler_range(1),delay_range(3)) + ...
                       A_eff(doppler_range(2),delay_range(3)) + ...
                       A_eff(doppler_range(3),delay_range(3)) + ...
                       (1-abs(doppler_frac))*A_eff(doppler_range(4),delay_range(3)) + ...
                       abs(doppler_frac)*delay_frac*A_eff(doppler_range(1),delay_range(4)) + ...
                       delay_frac*A_eff(doppler_range(2),delay_range(4)) + ...
                       delay_frac*A_eff(doppler_range(3),delay_range(4)) + ...
                       delay_frac*(1-abs(doppler_frac))*A_eff(doppler_range(4),delay_range(4));

end